branch-defaults:
  default:
    environment: mohit-dot-spring-aws
  master:
    environment: mohit-dot-spring-aws
deploy:
  artifact: target/task-manager-0.0.1-SNAPSHOT.jar
environment-defaults:
  mohit-dot-spring-aws:
    branch: null
    repository: null
global:
  application_name: spring-aws-mohit-app
  branch: null
  default_ec2_keyname: null
  default_platform: Java 8
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
